### ISSUE TITLE
Block document changed for PoW

### ISSUE THREAD

**Issue by c-geek** [duniter/duniter-python-api#18]
Initial issue in https://github.com/ucoin-io/ucoin/issues/268

---

Protocol rules:
- https://github.com/ucoin-io/ucoin/blob/master/doc/Protocol.md#structure
- https://github.com/ucoin-io/ucoin/blob/master/doc/Protocol.md#innerhash
- https://github.com/ucoin-io/ucoin/blob/master/doc/Protocol.md#block-fingerprint
- https://github.com/ucoin-io/ucoin/blob/master/doc/Protocol.md#signature

So now, the Nonce field is at the bottom of the Block, along with a InnerHash field. The behavior is the one described in the above 4 links:
- InnerHash is the hash of the "inner" part of the block
- Signature is made on InnerHash + Nonce

**Comment by Insoleet** [comment]
The blockUID is made of block hash or block inner hash ?

**Comment by c-geek** [comment]
Block hash.
