### ISSUE TITLE
Document how to use this lib

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter-python-api#27]
There is nearly no documentation how to use this lib.
It would be great to explain how to send a transaction at least.

Finally, points which needs to be documented:
- Send a transaction
- Send a certification
- Send request to join the community
- Send request to leave the community
- How to request the API

For instance, a [well documented python package](https://pypi.python.org/pypi/tabulate).

**Comment by vtexier** [comment]
I've written some examples on the [wiki](https://github.com/duniter/duniter-python-api/wiki).

These examples are also in a folder for easier use (see [this pull request](https://github.com/duniter/duniter-python-api/pull/30))

**Comment by vtexier** [comment]
Wiki is too hard to maintain so it is hidden.

Use examples scripts from the `examples` folder.
