### ISSUE TITLE
Request data example is not working

### ISSUE THREAD

**Issue by M5oul** [duniter/duniter-python-api#36]
https://github.com/duniter/duniter-python-api/wiki/Request-data is not working

```python
python3 test.py 
Creating a client session outside of coroutine
client_session: <aiohttp.client.ClientSession object at 0x7f0b62d151d0>
Traceback (most recent call last):
  File "test.py", line 44, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/lib64/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib64/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib64/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "test.py", line 29, in main
    response = await bma.node.Summary(connection).get(AIOHTTP_SESSION)
AttributeError: module 'duniterpy.api.bma.node' has no attribute 'Summary'

```

**Comment by vtexier** [comment]
Yes, examples in the wiki are for the old version of the api.

I need to copy/paste the new examples from the example folder to the wiki.

In the meantime, if you want to test examples, please use and adapt scripts from the examples folder.

https://github.com/duniter/duniter-python-api/tree/master/examples

**Comment by M5oul** [comment]
Ah, nice, thanks.

**Comment by M5oul** [comment]
I prefer using documentation on the git repository than on the wiki.
On the wiki, we could loose this information.
On git, we could easily see diff.
It's not needed to update the wiki.

**Comment by M5oul** [comment]
Ok, it works fine.

**Comment by M5oul** [comment]
I propose to not maintain the wiki.
Are you agree if we hide it?

**Comment by vtexier** [comment]
Yes I am.

**Comment by M5oul** [comment]
Done.
